/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-05 at 20:50:03 UTC 
 * Modify at your own risk.
 */

package com.noisyflowers.landpks.server.gae.model.plotendpoint;

/**
 * Service definition for Plotendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlotendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Plotendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the plotendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://silicon-bivouac-496.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "plotendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Plotendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Plotendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPhotoUploadURL".
   *
   * This request holds the parameters needed by the plotendpoint server.  After setting any optional
   * parameters, call the {@link GetPhotoUploadURL#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetPhotoUploadURL getPhotoUploadURL() throws java.io.IOException {
    GetPhotoUploadURL result = new GetPhotoUploadURL();
    initialize(result);
    return result;
  }

  public class GetPhotoUploadURL extends PlotendpointRequest<com.noisyflowers.landpks.server.gae.model.plotendpoint.model.StringReturn> {

    private static final String REST_PATH = "stringreturn";

    /**
     * Create a request for the method "getPhotoUploadURL".
     *
     * This request holds the parameters needed by the the plotendpoint server.  After setting any
     * optional parameters, call the {@link GetPhotoUploadURL#execute()} method to invoke the remote
     * operation. <p> {@link GetPhotoUploadURL#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetPhotoUploadURL() {
      super(Plotendpoint.this, "GET", REST_PATH, null, com.noisyflowers.landpks.server.gae.model.plotendpoint.model.StringReturn.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPhotoUploadURL setAlt(java.lang.String alt) {
      return (GetPhotoUploadURL) super.setAlt(alt);
    }

    @Override
    public GetPhotoUploadURL setFields(java.lang.String fields) {
      return (GetPhotoUploadURL) super.setFields(fields);
    }

    @Override
    public GetPhotoUploadURL setKey(java.lang.String key) {
      return (GetPhotoUploadURL) super.setKey(key);
    }

    @Override
    public GetPhotoUploadURL setOauthToken(java.lang.String oauthToken) {
      return (GetPhotoUploadURL) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPhotoUploadURL setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPhotoUploadURL) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPhotoUploadURL setQuotaUser(java.lang.String quotaUser) {
      return (GetPhotoUploadURL) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPhotoUploadURL setUserIp(java.lang.String userIp) {
      return (GetPhotoUploadURL) super.setUserIp(userIp);
    }

    @Override
    public GetPhotoUploadURL set(String parameterName, Object value) {
      return (GetPhotoUploadURL) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPlot".
   *
   * This request holds the parameters needed by the plotendpoint server.  After setting any optional
   * parameters, call the {@link GetPlot#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPlot getPlot(java.lang.String id) throws java.io.IOException {
    GetPlot result = new GetPlot(id);
    initialize(result);
    return result;
  }

  public class GetPlot extends PlotendpointRequest<com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot> {

    private static final String REST_PATH = "plot/{id}";

    /**
     * Create a request for the method "getPlot".
     *
     * This request holds the parameters needed by the the plotendpoint server.  After setting any
     * optional parameters, call the {@link GetPlot#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetPlot#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPlot(java.lang.String id) {
      super(Plotendpoint.this, "GET", REST_PATH, null, com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPlot setAlt(java.lang.String alt) {
      return (GetPlot) super.setAlt(alt);
    }

    @Override
    public GetPlot setFields(java.lang.String fields) {
      return (GetPlot) super.setFields(fields);
    }

    @Override
    public GetPlot setKey(java.lang.String key) {
      return (GetPlot) super.setKey(key);
    }

    @Override
    public GetPlot setOauthToken(java.lang.String oauthToken) {
      return (GetPlot) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPlot setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPlot) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPlot setQuotaUser(java.lang.String quotaUser) {
      return (GetPlot) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPlot setUserIp(java.lang.String userIp) {
      return (GetPlot) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetPlot setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPlot set(String parameterName, Object value) {
      return (GetPlot) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPlot".
   *
   * This request holds the parameters needed by the plotendpoint server.  After setting any optional
   * parameters, call the {@link InsertPlot#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot}
   * @return the request
   */
  public InsertPlot insertPlot(com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot content) throws java.io.IOException {
    InsertPlot result = new InsertPlot(content);
    initialize(result);
    return result;
  }

  public class InsertPlot extends PlotendpointRequest<com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot> {

    private static final String REST_PATH = "plot";

    /**
     * Create a request for the method "insertPlot".
     *
     * This request holds the parameters needed by the the plotendpoint server.  After setting any
     * optional parameters, call the {@link InsertPlot#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPlot#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot}
     * @since 1.13
     */
    protected InsertPlot(com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot content) {
      super(Plotendpoint.this, "POST", REST_PATH, content, com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot.class);
    }

    @Override
    public InsertPlot setAlt(java.lang.String alt) {
      return (InsertPlot) super.setAlt(alt);
    }

    @Override
    public InsertPlot setFields(java.lang.String fields) {
      return (InsertPlot) super.setFields(fields);
    }

    @Override
    public InsertPlot setKey(java.lang.String key) {
      return (InsertPlot) super.setKey(key);
    }

    @Override
    public InsertPlot setOauthToken(java.lang.String oauthToken) {
      return (InsertPlot) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPlot setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPlot) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPlot setQuotaUser(java.lang.String quotaUser) {
      return (InsertPlot) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPlot setUserIp(java.lang.String userIp) {
      return (InsertPlot) super.setUserIp(userIp);
    }

    @Override
    public InsertPlot set(String parameterName, Object value) {
      return (InsertPlot) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPlot".
   *
   * This request holds the parameters needed by the plotendpoint server.  After setting any optional
   * parameters, call the {@link ListPlot#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListPlot listPlot() throws java.io.IOException {
    ListPlot result = new ListPlot();
    initialize(result);
    return result;
  }

  public class ListPlot extends PlotendpointRequest<com.noisyflowers.landpks.server.gae.model.plotendpoint.model.CollectionResponsePlot> {

    private static final String REST_PATH = "plot";

    /**
     * Create a request for the method "listPlot".
     *
     * This request holds the parameters needed by the the plotendpoint server.  After setting any
     * optional parameters, call the {@link ListPlot#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListPlot#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPlot() {
      super(Plotendpoint.this, "GET", REST_PATH, null, com.noisyflowers.landpks.server.gae.model.plotendpoint.model.CollectionResponsePlot.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPlot setAlt(java.lang.String alt) {
      return (ListPlot) super.setAlt(alt);
    }

    @Override
    public ListPlot setFields(java.lang.String fields) {
      return (ListPlot) super.setFields(fields);
    }

    @Override
    public ListPlot setKey(java.lang.String key) {
      return (ListPlot) super.setKey(key);
    }

    @Override
    public ListPlot setOauthToken(java.lang.String oauthToken) {
      return (ListPlot) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPlot setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPlot) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPlot setQuotaUser(java.lang.String quotaUser) {
      return (ListPlot) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPlot setUserIp(java.lang.String userIp) {
      return (ListPlot) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPlot setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPlot setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime afterDate;

    /**

     */
    public com.google.api.client.util.DateTime getAfterDate() {
      return afterDate;
    }

    public ListPlot setAfterDate(com.google.api.client.util.DateTime afterDate) {
      this.afterDate = afterDate;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean allUsers;

    /**

     */
    public java.lang.Boolean getAllUsers() {
      return allUsers;
    }

    public ListPlot setAllUsers(java.lang.Boolean allUsers) {
      this.allUsers = allUsers;
      return this;
    }

    @Override
    public ListPlot set(String parameterName, Object value) {
      return (ListPlot) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlot".
   *
   * This request holds the parameters needed by the plotendpoint server.  After setting any optional
   * parameters, call the {@link RemovePlot#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlot removePlot(java.lang.String id) throws java.io.IOException {
    RemovePlot result = new RemovePlot(id);
    initialize(result);
    return result;
  }

  public class RemovePlot extends PlotendpointRequest<Void> {

    private static final String REST_PATH = "plot/{id}";

    /**
     * Create a request for the method "removePlot".
     *
     * This request holds the parameters needed by the the plotendpoint server.  After setting any
     * optional parameters, call the {@link RemovePlot#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePlot#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlot(java.lang.String id) {
      super(Plotendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlot setAlt(java.lang.String alt) {
      return (RemovePlot) super.setAlt(alt);
    }

    @Override
    public RemovePlot setFields(java.lang.String fields) {
      return (RemovePlot) super.setFields(fields);
    }

    @Override
    public RemovePlot setKey(java.lang.String key) {
      return (RemovePlot) super.setKey(key);
    }

    @Override
    public RemovePlot setOauthToken(java.lang.String oauthToken) {
      return (RemovePlot) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlot setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlot) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlot setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlot) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlot setUserIp(java.lang.String userIp) {
      return (RemovePlot) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemovePlot setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlot set(String parameterName, Object value) {
      return (RemovePlot) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePlot".
   *
   * This request holds the parameters needed by the plotendpoint server.  After setting any optional
   * parameters, call the {@link UpdatePlot#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot}
   * @return the request
   */
  public UpdatePlot updatePlot(com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot content) throws java.io.IOException {
    UpdatePlot result = new UpdatePlot(content);
    initialize(result);
    return result;
  }

  public class UpdatePlot extends PlotendpointRequest<com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot> {

    private static final String REST_PATH = "plot";

    /**
     * Create a request for the method "updatePlot".
     *
     * This request holds the parameters needed by the the plotendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePlot#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePlot#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot}
     * @since 1.13
     */
    protected UpdatePlot(com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot content) {
      super(Plotendpoint.this, "PUT", REST_PATH, content, com.noisyflowers.landpks.server.gae.model.plotendpoint.model.Plot.class);
    }

    @Override
    public UpdatePlot setAlt(java.lang.String alt) {
      return (UpdatePlot) super.setAlt(alt);
    }

    @Override
    public UpdatePlot setFields(java.lang.String fields) {
      return (UpdatePlot) super.setFields(fields);
    }

    @Override
    public UpdatePlot setKey(java.lang.String key) {
      return (UpdatePlot) super.setKey(key);
    }

    @Override
    public UpdatePlot setOauthToken(java.lang.String oauthToken) {
      return (UpdatePlot) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePlot setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePlot) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePlot setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePlot) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePlot setUserIp(java.lang.String userIp) {
      return (UpdatePlot) super.setUserIp(userIp);
    }

    @Override
    public UpdatePlot set(String parameterName, Object value) {
      return (UpdatePlot) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Plotendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Plotendpoint}. */
    @Override
    public Plotendpoint build() {
      return new Plotendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlotendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlotendpointRequestInitializer(
        PlotendpointRequestInitializer plotendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(plotendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
