/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-26 at 04:16:56 UTC 
 * Modify at your own risk.
 */

package com.noisyflowers.landpks.server.gae.model.transectendpoint.model;

/**
 * Model definition for Segment.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the transectendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Segment extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean basalGap;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean canopyGap;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String canopyHeight;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String range;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer species1Density;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer species2Density;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> speciesList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<StickSegment> stickSegments;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Transect transect;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getBasalGap() {
    return basalGap;
  }

  /**
   * @param basalGap basalGap or {@code null} for none
   */
  public Segment setBasalGap(java.lang.Boolean basalGap) {
    this.basalGap = basalGap;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanopyGap() {
    return canopyGap;
  }

  /**
   * @param canopyGap canopyGap or {@code null} for none
   */
  public Segment setCanopyGap(java.lang.Boolean canopyGap) {
    this.canopyGap = canopyGap;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCanopyHeight() {
    return canopyHeight;
  }

  /**
   * @param canopyHeight canopyHeight or {@code null} for none
   */
  public Segment setCanopyHeight(java.lang.String canopyHeight) {
    this.canopyHeight = canopyHeight;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public Segment setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Segment setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRange() {
    return range;
  }

  /**
   * @param range range or {@code null} for none
   */
  public Segment setRange(java.lang.String range) {
    this.range = range;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSpecies1Density() {
    return species1Density;
  }

  /**
   * @param species1Density species1Density or {@code null} for none
   */
  public Segment setSpecies1Density(java.lang.Integer species1Density) {
    this.species1Density = species1Density;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSpecies2Density() {
    return species2Density;
  }

  /**
   * @param species2Density species2Density or {@code null} for none
   */
  public Segment setSpecies2Density(java.lang.Integer species2Density) {
    this.species2Density = species2Density;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getSpeciesList() {
    return speciesList;
  }

  /**
   * @param speciesList speciesList or {@code null} for none
   */
  public Segment setSpeciesList(java.util.List<java.lang.String> speciesList) {
    this.speciesList = speciesList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<StickSegment> getStickSegments() {
    return stickSegments;
  }

  /**
   * @param stickSegments stickSegments or {@code null} for none
   */
  public Segment setStickSegments(java.util.List<StickSegment> stickSegments) {
    this.stickSegments = stickSegments;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Transect getTransect() {
    return transect;
  }

  /**
   * @param transect transect or {@code null} for none
   */
  public Segment setTransect(Transect transect) {
    this.transect = transect;
    return this;
  }

  @Override
  public Segment set(String fieldName, Object value) {
    return (Segment) super.set(fieldName, value);
  }

  @Override
  public Segment clone() {
    return (Segment) super.clone();
  }

}
